name: gps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Paket-paket yang digunakan
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
